quarkus.banner.enabled=false
quarkus.log.level=WARN

# Blue Hat cloud configuration
attimo.bluehat.host-name=localhost
attimo.bluehat.repository=https://github.com/attimo/bluehat.git
attimo.bluehat.local-port=18080
